#!/bin/bash
# Battery blocklet for Regolith
# This script was adapted from https://github.com/hastinbe/i3blocks-battery-plus

LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

# Get battery status.
#
# Returns:
#   The battery's status or state.
get_battery_status() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "state:" {print $2}'
}

# Get battery percentage.
#
# Returns:
#   The battery's percentage, without the %.
get_battery_percent() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "percentage:" { gsub("%","",$2); print $2}'
}

BATT_DEVICE=$(upower -e | grep -o 'BAT[0-9]' | head -n 1)
__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")

BATT_PERCENT=$(get_battery_percent)
CHARGE_STATE=$(get_battery_status)

#DEBUG_BATTERY=1
if [ ! -z $DEBUG_BATTERY ]; then
    BATT_PERCENT=10
    CHARGE_STATE="discharging"
fi

if [ -z "$BATT_PERCENT" ]; then
    exit 0
elif [ "$BATT_PERCENT" -ge 0 ] && [ "$BATT_PERCENT" -le 20 ]; then
    LABEL_ICON=$(xrescat i3xrocks.label.battery0 E)
    VALUE_COLOR=$(xrescat i3xrocks.critical.color red)
    LABEL_COLOR=$VALUE_COLOR
elif [ "$BATT_PERCENT" -ge 20 ] && [ "$BATT_PERCENT" -le 50 ]; then
    LABEL_ICON=$(xrescat i3xrocks.label.battery20 L)
    VALUE_COLOR=$(xrescat i3xrocks.error.color orange)
    LABEL_COLOR=$VALUE_COLOR
elif [ "$BATT_PERCENT" -ge 50 ] && [ "$BATT_PERCENT" -le 80 ]; then
    LABEL_ICON=$(xrescat i3xrocks.label.battery50 M)
    VALUE_COLOR=$(xrescat i3xrocks.nominal white)
    LABEL_COLOR=$VALUE_COLOR
elif [ "$BATT_PERCENT" -ge 80 ] && [ "$BATT_PERCENT" -le 98 ]; then
    LABEL_ICON=$(xrescat i3xrocks.label.battery80 F)
    VALUE_COLOR=$(xrescat i3xrocks.label.color white)
    LABEL_COLOR=$VALUE_COLOR
else
    LABEL_ICON=$(xrescat i3xrocks.label.battery100 C)
    VALUE_COLOR=$(xrescat i3xrocks.label.color white)
    LABEL_COLOR=$VALUE_COLOR
fi

if [ -z "$CHARGE_STATE" ]; then
    exit 0
elif [ "$CHARGE_STATE" == "discharging" ]; then
    CHARGE_ICON=$(xrescat i3xrocks.label.dn D)
elif [ "$CHARGE_STATE" == "charging" ]; then
    CHARGE_ICON=$(xrescat i3xrocks.label.up C)
else
    CHARGE_ICON=$(echo -e '\u2003')
fi

ICON_SPAN="<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span>"
VALUE_SPAN="<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $BATT_PERCENT%</span>"
CHARGE_SPAN="<span color=\"${LABEL_COLOR}\">$CHARGE_ICON</span>"

echo "${ICON_SPAN}${VALUE_SPAN}${CHARGE_SPAN}"

case "$button" in
1) # Handle left click, default to launch power settings
    LEFT_CLICK_ACTION=$(xrescat i3xrocks.battery.left_click_action "$(which gnome-control-center) power")
    [[ ! -z $LEFT_CLICK_ACTION ]] && $(which i3-msg) -q exec "$LEFT_CLICK_ACTION" ;;
2) # Handle middle click, default to no action
    MIDDLE_CLICK_ACTION=$(xrescat i3xrocks.battery.middle_click_action "")
    [[ ! -z $MIDDLE_CLICK_ACTION ]] && $(which i3-msg) -q exec "$MIDDLE_CLICK_ACTION" ;;
3) # Handle right click, default to no action
    RIGHT_CLICK_ACTION=$(xrescat i3xrocks.battery.right_click_action "")
    [[ ! -z $RIGHT_CLICK_ACTION ]] && $(which i3-msg) -q exec "$RIGHT_CLICK_ACTION" ;;
4) # Handle scroll up, default to no action
    SCROLL_UP_ACTION=$(xrescat i3xrocks.battery.scroll_up_action "")
    [[ ! -z $SCROLL_UP_ACTION ]] && $(which i3-msg) -q exec "$SCROLL_UP_ACTION" ;;
5) # Handle scroll down, default to no action
    SCROLL_DOWN_ACTION=$(xrescat i3xrocks.battery.scroll_down_action "")
    [[ ! -z $SCROLL_DOWN_ACTION ]] && $(which i3-msg) -q exec "$SCROLL_DOWN_ACTION" ;;
esac
